# permissions for end users to edit ingresses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ingress-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: goingressmonitor
    app.kubernetes.io/part-of: goingressmonitor
    app.kubernetes.io/managed-by: kustomize
  name: ingress-editor-role
rules:
- apiGroups:
  - network.example.com
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.example.com
  resources:
  - ingresses/status
  verbs:
  - get
