name: Operator CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21.5' 

    - name: Install Operator SDK
      run: |
        export ARCH=$(case $(uname -m) in x86_64) echo -n amd64 ;; aarch64) echo -n arm64 ;; *) echo -n $(uname -m) ;; esac)
        export OS=$(uname | awk '{print tolower($0)}')
        export OPERATOR_SDK_DL_URL=https://github.com/operator-framework/operator-sdk/releases/download/v1.33.0
        curl -LO ${OPERATOR_SDK_DL_URL}/operator-sdk_${OS}_${ARCH}
        chmod +x operator-sdk_${OS}_${ARCH} && sudo mv operator-sdk_${OS}_${ARCH} /usr/local/bin/operator-sdk

    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build Operator Docker Image
      run: |
        make docker-build IMG="madistestk8s/pipeline_test:${{ github.run_number }}"

    - name: Push Docker Image
      run: |
        docker push madistestk8s/pipeline_test:${{ github.run_number }}

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GKE_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: '>= 363.0.0'  

    - name: Set up Kubectl
      run: |
        gcloud container clusters get-credentials autopilot-cluster-1 --region europe-central2 --project kubernetes-410020
    
    - name: Install Google Cloud SDK components
      run: |
        gcloud components install gke-gcloud-auth-plugin
    #CRD is not needed for a workflow but for personal reference
    # - name: Apply CRD
    #   run: |
    #      kubectl apply -f config/crd/bases/network.example.com_ingresses.yaml
    
    # # Not Nessessary for a workflow but for personal reference
    # - name: Apply Role for Operator Permissions
    #   run: |
    #       kubectl apply -f deployments/role.yaml

    # - name: Apply RoleBinding for Operator Permissions
    #   run: |
    #        kubectl apply -f deployments/rolebinding.yaml

    # - name: Apply RoleBinding for Operator Permissions Cluster Wide
    #   run: |
    #        kubectl apply -f deployments/clusterrole.yaml

    # - name: Apply RoleBinding for Operator Permissions Cluster WideË‡
    #   run: |
    #        kubectl apply -f deployments/clusterrolebinding.yaml

    - name: Update Deployment Image
      run: |
        sed -i 's|madistestk8s/pipeline_test:TAG_PLACEHOLDER|madistestk8s/pipeline_test:${{ github.run_number }}|' operatorDeployment.yaml



    - name: Deploy Operator
      run: |
        kubectl apply -f operatorDeployment.yaml


